name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'      
    - name: Build with Gradle
      run: ./gradlew packageDistribution
    - uses: actions/upload-artifact@v4
      with:
        name: helios-SNAPSHOT-${{ github.sha }}-${{ github.run_number }}
        path: build/dist
